set -s escape-time 0
set -g mouse on
set -g display-time 4000
set -g display-panes-time 4000
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -s set-clipboard on

set -g status-keys vi
setw -g mode-keys vi

bind = select-layout even-horizontal
bind s run-shell "/etc/tmux/popup.sh"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'

set-hook -g session-created 'run-shell "/etc/tmux/renumber-sess.sh"'
set-hook -g session-closed  'run-shell "/etc/tmux/renumber-sess.sh"'
set-hook -g session-renamed 'run-shell "/etc/tmux/renumber-sess.sh"'

run '~/.tmux/plugins/tpm/tpm'
